#! /bin/bash


source /etc/profile.d/tags-to-env.sh

export GIT_WORK_TREE=/var/www/
export GIT_REPO_TREE=$(pwd)
git checkout -f
cd $GIT_WORK_TREE

export NVM_DIR = ~/.nvm
source ~/.nvm/nvm.sh

echo "[+] install node version"
nvm install 4.4.4

echo "[+] Installing dependencies "
npm install

echo "[+] restarting app"
pm2 restart app

echo "[+] deployed"
